export const indianFoodMap = {
  rice: { name: "Steamed Basmati Rice", calories: 130 },
  "eels on rice": { name: "Fish Pulao", calories: 180 },
  pilaf: { name: "Vegetable Pulao", calories: 140 },
  "chicken-'n'-egg on rice": {
    name: "Chicken Egg Bhurji with Rice",
    calories: 200,
  },
  "pork cutlet on rice": { name: "Pork Vindaloo with Rice", calories: 250 },
  "beef curry": { name: "Kerala Beef Curry with Rice", calories: 220 },
  sushi: { name: "Khandvi (Gujarati Sushi)", calories: 150 },
  "chicken rice": { name: "Chicken Biryani", calories: 190 },
  "fried rice": { name: "Jeera Rice", calories: 210 },
  "tempura bowl": { name: "Pakora Thali", calories: 280 },
  bibimbap: { name: "Bisi Bele Bath", calories: 220 },
  toast: { name: "Tandoori Roti", calories: 265 },
  croissant: { name: "Puri", calories: 406 },
  "roll bread": { name: "Pav", calories: 270 },
  "raisin bread": { name: "Methi Thepla", calories: 290 },
  "chip butty": { name: "Aloo Paratha", calories: 320 },
  hamburger: { name: "Vada Pav", calories: 250 },
  pizza: { name: "Masala Dosa", calories: 266 },
  sandwiches: { name: "Chutney Sandwich", calories: 250 },
  "udon noodle": { name: "Sevai Upma", calories: 130 },
  "tempura udon": { name: "Vegetable Sevai", calories: 270 },
  "soba noodle": { name: "Poha", calories: 140 },
  "ramen noodle": { name: "Masala Maggi", calories: 190 },
  "beef noodle": { name: "Kerala Beef Stew with Appam", calories: 200 },
  "tensin noodle": { name: "Kothu Parotta", calories: 180 },
  "fried noodle": { name: "Hakka Noodles", calories: 220 },
  spaghetti: { name: "Vermicelli Upma", calories: 160 },
  "Japanese-style pancake": { name: "Dosa", calories: 230 },
  takoyaki: { name: "Paniyaram", calories: 200 },
  gratin: { name: "Vegetable Au Gratin", calories: 180 },
  "sauteed vegetables": { name: "Stir-fried Subzi", calories: 80 },
  croquette: { name: "Aloo Tikki", calories: 240 },
  "grilled eggplant": { name: "Baingan Bharta", calories: 60 },
  "sauteed spinach": { name: "Palak Sabzi", calories: 50 },
  "vegetable tempura": { name: "Vegetable Pakora", calories: 160 },
  "miso soup": { name: "Dal Shorba", calories: 35 },
  potage: { name: "Tomato Soup", calories: 90 },
  sausage: { name: "Chicken Seekh Kebab", calories: 300 },
  oden: { name: "Sambar", calories: 120 },
  omelet: { name: "Masala Omelet", calories: 150 },
  ganmodoki: { name: "Methi Muthia", calories: 180 },
  jiaozi: { name: "Momo", calories: 200 },
  stew: { name: "Vegetable Stew", calories: 120 },
  "teriyaki grilled fish": { name: "Tandoori Fish", calories: 170 },
  "fried fish": { name: "Fish Fry", calories: 220 },
  "grilled salmon": { name: "Tandoori Salmon", calories: 200 },
  "salmon meuniere": { name: "Fish Amritsari", calories: 230 },
  sashimi: { name: "Surmai Sashimi", calories: 120 },
  "grilled pacific saury": { name: "Grilled Surmai", calories: 180 },
  sukiyaki: { name: "Mutton Sukka", calories: 250 },
  "sweet and sour pork": { name: "Pork Vindaloo", calories: 260 },
  "lightly roasted fish": { name: "Tawa Fish", calories: 160 },
  "steamed egg hotchpotch": { name: "Egg Bhurji", calories: 90 },
  tempura: { name: "Vegetable Pakora", calories: 220 },
  "fried chicken": { name: "Chicken 65", calories: 280 },
  "sirloin cutlet": { name: "Beef Cutlet", calories: 300 },
  nanbanzuke: { name: "Fish Pickle", calories: 180 },
  "boiled fish": { name: "Fish Curry", calories: 140 },
  "seasoned beef with potatoes": { name: "Beef Ularthiyathu", calories: 190 },
  "hambarg steak": { name: "Kheema Pav", calories: 220 },
  steak: { name: "Tandoori Chicken", calories: 270 },
  "dried fish": { name: "Bombil Fry", calories: 290 },
  "ginger pork saute": { name: "Pork Pepper Fry", calories: 240 },
  "spicy chili-flavored tofu": { name: "Chilli Paneer", calories: 120 },
  yakitori: { name: "Tandoori Chicken", calories: 180 },
  "cabbage roll": { name: "Cabbage Kofta", calories: 150 },
  omelet: { name: "Masala Omelet", calories: 150 },
  "egg sunny-side up": { name: "Anda Fry", calories: 140 },
  natto: { name: "Fermented Urad Dal", calories: 200 },
  "cold tofu": { name: "Chhena", calories: 70 },
  "egg roll": { name: "Egg Roll", calories: 220 },
  "chilled noodle": { name: "Cold Poha", calories: 130 },
  "stir-fried beef and peppers": { name: "Beef Jalfrezi", calories: 180 },
  "simmered pork": { name: "Pork Curry", calories: 250 },
  "boiled chicken and vegetables": { name: "Chicken Stew", calories: 140 },
  "sashimi bowl": { name: "Thalipeeth", calories: 200 },
  "sushi bowl": { name: "Poha Bowl", calories: 220 },
  "fish-shaped pancake with bean jam": { name: "Modak", calories: 240 },
  "shrimp with chill source": { name: "Prawns Masala", calories: 180 },
  "roast chicken": { name: "Tandoori Chicken", calories: 220 },
  "steamed meat dumpling": { name: "Momo", calories: 200 },
  "omelet with fried rice": { name: "Egg Fried Rice", calories: 250 },
  "cutlet curry": { name: "Cutlet Curry", calories: 280 },
  "spaghetti meat sauce": { name: "Keema Pav", calories: 180 },
  "fried shrimp": { name: "Prawns Fry", calories: 240 },
  "potato salad": { name: "Aloo Chaat", calories: 140 },
  "green salad": { name: "Kachumber Salad", calories: 50 },
  "macaroni salad": { name: "Sewai Salad", calories: 160 },
  "Japanese tofu and vegetable chowder": { name: "Dal Dhokli", calories: 90 },
  "pork miso soup": { name: "Pork Rasam", calories: 100 },
  "chinese soup": { name: "Manchow Soup", calories: 70 },
  "beef bowl": { name: "Keema Rice", calories: 220 },
  "kinpira-style sauteed burdock": {
    name: "Stir-fried Lotus Root",
    calories: 120,
  },
  "rice ball": { name: "Poha Laddu", calories: 170 },
  "pizza toast": { name: "Masala Toast", calories: 280 },
  "dipping noodles": { name: "Idiyappam with Curry", calories: 190 },
  "hot dog": { name: "Frankie Roll", calories: 290 },
  "french fries": { name: "Aloo Chips", calories: 312 },
  "mixed rice": { name: "Vegetable Pulao", calories: 180 },
  "goya chanpuru": { name: "Karela Sabzi", calories: 150 },
  "green curry": { name: "Hariyali Chicken", calories: 200 },
  "okinawa soba": { name: "Kothu Parotta", calories: 170 },
  "mango pudding": { name: "Aamras", calories: 150 },
  "almond jelly": { name: "Badam Halwa", calories: 120 },
  jjigae: { name: "Sambar", calories: 180 },
  "dak galbi": { name: "Chicken Chettinad", calories: 220 },
  "dry curry": { name: "Sukha Bhel", calories: 210 },
  kamameshi: { name: "Vegetable Biryani", calories: 190 },
  "rice vermicelli": { name: "Sevai", calories: 140 },
  paella: { name: "Vegetable Pulao", calories: 220 },
  tanmen: { name: "Vegetable Noodles", calories: 180 },
  kushikatu: { name: "Paneer Tikka", calories: 300 },
  "yellow curry": { name: "Dal Tadka", calories: 210 },
  pancake: { name: "Dosa", calories: 230 },
  champon: { name: "Hakka Noodles", calories: 190 },
  crape: { name: "Malpua", calories: 220 },
  tiramisu: { name: "Gulab Jamun", calories: 350 },
  waffle: { name: "Pesarattu", calories: 310 },
  "rare cheese cake": { name: "Rasmalai", calories: 320 },
  shortcake: { name: "Mysore Pak", calories: 340 },
  "chop suey": { name: "Hakka Noodles", calories: 150 },
  "twice cooked pork": { name: "Pork Vindaloo", calories: 280 },
  "mushroom risotto": { name: "Mushroom Biryani", calories: 180 },
  samul: { name: "Vegetable Pulao", calories: 160 },
  zoni: { name: "Pongal", calories: 140 },
  "french toast": { name: "Bombay Toast", calories: 260 },
  "fine white noodles": { name: "Idiyappam", calories: 150 },
  minestrone: { name: "Tomato Saar", calories: 90 },
  "pot au feu": { name: "Yakhni", calories: 120 },
  "chicken nugget": { name: "Chicken Tikka", calories: 290 },

  namero: { name: "Kerala Fish Curry", calories: 180 },
  "french bread": { name: "Naan", calories: 270 },
  "rice gruel": { name: "Kanji", calories: 60 },
  "broiled eel bowl": { name: "Fish Biryani", calories: 280 },
  "clear soup": { name: "Rasam", calories: 30 },
  yudofu: { name: "Paneer Curry", calories: 80 },
  mozuku: { name: "Seaweed Chutney", calories: 40 },
  inarizushi: { name: "Masala Vada", calories: 200 },
  "pork loin cutlet": { name: "Pork Chops", calories: 300 },
  "pork fillet cutlet": { name: "Pork Roast", calories: 290 },
  "chicken cutlet": { name: "Kerala Chicken Cutlet", calories: 280 },
  "ham cutlet": { name: "Goan Ham Cutlet", calories: 270 },
  "minced meat cutlet": { name: "Keema Cutlet", calories: 290 },
  "thinly sliced raw horsemeat": { name: "Beef Chilli Fry", calories: 130 },
  bagel: { name: "Medu Vada", calories: 250 },
  scone: { name: "Nankhatai Biscuit", calories: 340 },
  tortilla: { name: "Roomali Roti", calories: 220 },
  tacos: { name: "Masala Roti Wrap", calories: 230 },
  nachos: { name: "Papdi Chaat", calories: 300 },
  "meat loaf": { name: "Mutton Loaf", calories: 240 },
  "scrambled egg": { name: "Anda Bhurji", calories: 150 },
  "rice gratin": { name: "Baked Vegetable Biryani", calories: 200 },
  lasagna: { name: "Paneer Lasagna", calories: 180 },
  "Caesar salad": { name: "Paneer Tikka Salad", calories: 150 },
  oatmeal: { name: "Dalia Porridge", calories: 70 },
  "fried pork dumplings served in soup": {
    name: "Pork Momos in Broth",
    calories: 220,
  },
  oshiruko: { name: "Moong‑dal Payasam", calories: 160 },
  muffin: { name: "Banana Muffin", calories: 350 },
  popcorn: { name: "Masala Popcorn", calories: 375 },
  "cream puff": { name: "Cream Roll", calories: 320 },

  doughnut: { name: "Balushahi", calories: 380 },
  "apple pie": { name: "Apple Gujiya", calories: 240 },
  parfait: { name: "Fruit Falooda", calories: 280 },
  "fried pork in scoop": { name: "Pork Chilli Fry", calories: 290 },
  "lamb kebabs": { name: "Mutton Seekh Kebab", calories: 220 },
  "dish consisting of stir-fried potato, eggplant and green pepper": {
    name: "Aloo‑Baingan Capsicum",
    calories: 120,
  },
  "roast duck": { name: "Tandoori Duck", calories: 300 },
  "hot pot": { name: "Kerala Ishtu (Stew)", calories: 180 },
  "pork belly": { name: "Pork Roast Masala", calories: 330 },
  "xiao long bao": { name: "Pork Momos", calories: 200 },
  "moon cake": { name: "Chandrakala", calories: 350 },
  "custard tart": { name: "Goan Bebinca", calories: 300 },
  "beef noodle soup": { name: "Beef Shorba Noodles", calories: 190 },
  "pork cutlet": { name: "Goan Pork Cutlet", calories: 290 },
  "minced pork rice": { name: "Pork Keema Rice", calories: 250 },
  "fish ball soup": { name: "Fish Kofta Shorba", calories: 120 },
  "oyster omelette": { name: "Prawn Omelette", calories: 220 },
  "glutinous oil rice": { name: "Sticky Ghee Pulao", calories: 280 },
  "trunip pudding": { name: "Shalgam Halwa", calories: 120 },
  "stinky tofu": { name: "Fermented Paneer", calories: 160 },
  "lemon fig jelly": { name: "Lemon‑Fig Halwa", calories: 140 },
  "khao soi": { name: "Coconut Curry Noodles", calories: 220 },
  "Sour prawn soup": { name: "Prawn Rasam", calories: 150 },
  "Thai papaya salad": { name: "Papaya Kachumber", calories: 80 },
  "boned, sliced Hainan-style chicken with marinated rice": {
    name: "Steamed Chicken Pulao",
    calories: 230,
  },
  "hot and sour, fish and vegetable ragout": {
    name: "Hot‑&‑Sour Fish Curry",
    calories: 180,
  },
  "stir-fried mixed vegetables": { name: "Mixed Veg Sabzi", calories: 90 },
  "beef in oyster sauce": { name: "Beef Pepper Masala", calories: 200 },
  "pork satay": { name: "Pork Tikka Skewers", calories: 280 },
  "spicy chicken salad": { name: "Spicy Chicken Chaat", calories: 150 },
  "noodles with fish curry": { name: "Meen Curry Noodles", calories: 210 },
  "Pork Sticky Noodles": { name: "Pork Sevai", calories: 240 },
  "Pork with lemon": { name: "Lemon Pork Fry", calories: 220 },
  "stewed pork leg": { name: "Pork Leg Curry", calories: 300 },
  "charcoal-boiled pork neck": { name: "Smoked Pork Roast", calories: 280 },
  "fried mussel pancakes": { name: "Mussel Uttapam", calories: 250 },
  "Deep Fried Chicken Wing": { name: "Chicken Lollipop", calories: 320 },
  "Barbecued red pork in sauce with rice": {
    name: "Pork Vindaloo Rice",
    calories: 270,
  },
  "Rice with roast duck": { name: "Duck Biryani", calories: 290 },
  "Rice crispy pork": { name: "Crispy Pork Rice", calories: 310 },
  "Wonton soup": { name: "Chicken Momo Soup", calories: 120 },
  "Chicken Rice Curry With Coconut": {
    name: "Kerala Chicken Curry Rice",
    calories: 240,
  },
  "Crispy Noodles": { name: "Crispy Hakka Noodles", calories: 280 },
  "Egg Noodle In Chicken Yellow Curry": {
    name: "Egg Noodles with Chicken Curry",
    calories: 230,
  },
  "coconut milk soup": { name: "Coconut Milk Shorba", calories: 180 },
  pho: { name: "Nalli Nihari Soup", calories: 160 },
  "Hue beef rice vermicelli soup": { name: "Beef Sevai Soup", calories: 190 },
  "Vermicelli noodles with snails": {
    name: "Seafood Sevai Upma",
    calories: 200,
  },
  "Fried spring rolls": { name: "Veg Spring Roll", calories: 220 },
  "Steamed rice roll": { name: "Rice Pathiri Roll", calories: 150 },
  "Shrimp patties": { name: "Prawn Cutlet", calories: 180 },
  "ball shaped bun with pork": { name: "Pork Bao", calories: 250 },
  "Coconut milk-flavored crepes with shrimp and beef": {
    name: "Coconut Neer Dosa with Surf‑&‑Turf",
    calories: 230,
  },
  "Small steamed savory rice pancake": { name: "Mini Idli", calories: 160 },
  "Glutinous Rice Balls": { name: "Sweet Rice Laddu", calories: 200 },
  "loco moco": { name: "Keema Rice with Fried Egg", calories: 350 },
  haupia: { name: "Coconut Barfi", calories: 120 },
  malasada: { name: "Khoya Doughnut", calories: 380 },
  laulau: { name: "Leaf‑Wrapped Fish Parcel", calories: 220 },
  "spam musubi": { name: "Masala Rice Sushi", calories: 280 },
  "oxtail soup": { name: "Paya Soup", calories: 190 },
  adobo: { name: "Pork Achari", calories: 250 },
  lumpia: { name: "Chicken Spring Roll", calories: 200 },
  brownie: { name: "Chocolate Burfi", calories: 420 },
  churro: { name: "Jalebi", calories: 360 },
  jambalaya: { name: "Seafood Biryani", calories: 220 },
  "nasi goreng": { name: "Tawa Pulao", calories: 240 },
  "ayam goreng": { name: "Andhra Fried Chicken", calories: 280 },
  "ayam bakar": { name: "Tandoori Chicken Leg", calories: 260 },
  "bubur ayam": { name: "Chicken Kanji", calories: 150 },
  gulai: { name: "Mutton Rogan Josh", calories: 220 },
  laksa: { name: "Coconut Noodle Curry", calories: 280 },
  "mie ayam": { name: "Chicken Hakka Noodles", calories: 240 },
  "mie goreng": { name: "Veg Chow Mein", calories: 260 },
  "nasi campur": { name: "Mixed Curry Rice", calories: 250 },
  "nasi padang": { name: "Assorted Thali Rice", calories: 270 },
  "nasi uduk": { name: "Coconut Milk Pulao", calories: 240 },
  "babi guling": { name: "Goan Roast Pork", calories: 320 },
  "kaya toast": { name: "Jam Toast", calories: 280 },
  "bak kut teh": { name: "Pork Bone Rasam", calories: 220 },

  "curry puff": { name: "Veg Curry Puff (Samosa)", calories: 300 },
  "chow mein": { name: "Indian‑Style Chow Mein", calories: 240 },
  "zha jiang mian": { name: "Black‑Bean Masala Noodles", calories: 250 },
  "kung pao chicken": { name: "Chicken Chilli Dry", calories: 260 },
  crullers: { name: "Khaja", calories: 340 },
  "eggplant with garlic sauce": {
    name: "Baingan Garlic Masala",
    calories: 120,
  },
  "three cup chicken": { name: "Soy‑Ginger Chicken", calories: 280 },
  "bean curd family style": { name: "Paneer Kadai", calories: 150 },
  "salt & pepper fried shrimp with shell": {
    name: "Pepper Prawns Fry",
    calories: 220,
  },
  "baked salmon": { name: "Tandoori Salmon Bake", calories: 200 },
  "braised pork meat ball with napa cabbage": {
    name: "Pork Kofta Curry",
    calories: 240,
  },
  "winter melon soup": { name: "Ash Gourd Rasam", calories: 80 },
  "steamed spareribs": { name: "Steamed Pork Ribs Masala", calories: 280 },
  "chinese pumpkin pie": { name: "Pumpkin Halwa Pie", calories: 220 },
  "eight treasure rice": { name: "Dry‑Fruit Pulao", calories: 250 },
  "hot & sour soup": { name: "Hot & Sour Veg Soup", calories: 90 },
  _default: { name: "Indian Thali", calories: 350 },
};

export const getIndianDish = (originalName) => {
  return indianFoodMap[originalName.toLowerCase()] || indianFoodMap["_default"];
};
